---
title: "2-dates"
output: html_document
---

```{r}
pacman::p_load(
  lubridate,  # general package for handling and converting dates  
  parsedate,  # has function to "guess" messy dates
  aweek,      # another option for converting dates to weeks, and weeks to dates
  zoo,        # additional date/time functions
  here,       # file management
  rio,        # data import/export
  tidyverse
)
```

```{r}
linelist_cleaned <- import("/home/jeremy/Work/Development/Projects/epidemic/datasets/linelist_cleaned.xlsx")
linelist_raw <- import("/home/jeremy/Work/Development/Projects/epidemic/datasets/linelist_raw.xlsx")
head(linelist_cleaned)
head(linelist_raw)
```

```{r}
Sys.Date()
```

```{r}
Sys.time()
```

```{r}
names(linelist_cleaned)
names(linelist_raw)
```

```{r}
# Convert to class date
linelist <- linelist_cleaned %>% 
  mutate(date_onset = as.Date(date_onset, format = "%d/%m/%Y"))
```

```{r}
ymd("20241011")
mdy("10/11/2024")
dmy("11 10 2024")
dmy("11 October 2024")
```

```{r}
two_digit_years <- c("15", "15", "16", "17")
str_glue("20{two_digit_years}")
```

```{r}
linelist <- linelist %>% 
  mutate(onset_date = make_date(year = onset_year, month = onset_month, day = onset_day))
```

```{r}
# Providing the Excel 'origin date' when converting Excel number dates
linelist <- linelist %>% 
  mutate(date_onset = as.numeric(date_onset)) %>%   # ensure class is numeric
  mutate(date_onset = as.Date(date_onset, origin = "1899-12-30")) # convert to date using Excel origin
```

```{r}
# Using parse_date() on the column date_onset
linelist <- linelist %>%      
  mutate(date_onset = parse_date(date_onset))
```

```{r}
# packages
pacman::p_load(tidyverse, lubridate, stringr)

# time_admission is a column in hours:minutes
linelist <- linelist %>%
  # when time of admission is not given, assign the median admission time
  mutate(
    time_admission_clean = ifelse(
      is.na(time_admission),         # if time is missing
      median(time_admission),        # assign the median
      time_admission                 # if not missing keep as is
  )) %>%
  # use str_glue() to combine date and time columns to create one character column
  # and then use ymd_hm() to convert it to datetime
  mutate(
    date_time_of_admission = str_glue("{date_hospitalisation} {time_admission_clean}") %>% 
      ymd_hm()
  )
  
linelist
```

```{r}
# Extract Time
linelist <- linelist %>%
  mutate(hour_admit = hour(strptime(time_admission, format = "%H:%M"))) %>%
  mutate(time_period = case_when(
    hour_admit > 06 & hour_admit < 12 ~ "Morning",
    hour_admit >= 12 & hour_admit < 17 ~ "Afternoon",
    hour_admit >= 17 & hour_admit < 21 ~ "Evening",
    hour_admit >=21 | hour_admit <= 6 ~ "Night"))
```

```{r}
linelist <- linelist %>%
  mutate(date_onset = dmy(date_onset),
         date_hospitalisation = dmy(date_hospitalisation)) %>%
  filter(month(date_onset) == 3) %>%
  mutate(days_onset_to_hosp = date_hospitalisation - date_onset)
```

```{r}
names(linelist)
```

```{r}
median(linelist_delay$days_onset_to_hosp, na.rm = T)
```

```{r}
# create new column 
test_zoo <- linelist %>% 
     mutate(yearmonth = zoo::as.yearmon(date_onset))

# print table
table(test_zoo$yearmon)
```

```{r}
# create new column
test_format <- linelist %>% 
     mutate(yearmonth = format(date_onset, "%b %Y"))

# print table
table(test_format$yearmon)
```

```{r}
# Make aggregated dataset of weekly case counts
weekly_counts <- linelist %>% 
  drop_na(date_onset) %>%             # remove cases missing onset date
  mutate(weekly_cases = floor_date(   # make new column, week of onset
    date_onset,
    unit = "week")) %>%            
  count(weekly_cases) %>%           # group data by week and count rows per group (creates column 'n')
  tidyr::complete(                  # ensure all weeks are present, even those with no cases reported
    weekly_cases = seq.Date(          # re-define the "weekly_cases" column as a complete sequence,
      from = min(weekly_cases),       # from the minimum date
      to = max(weekly_cases),         # to the maxiumum date
      by = "week"),                   # by weeks
    fill = list(n = 0))             # fill-in NAs in the n counts column with 0

weekly_counts
```

```{r}

```
