---
title: "Pivoting Data"
output: html_document
date: "2025-05-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(
  rio,          # File import
  here,         # File locator
  kableExtra,   # Build and manipulate complex tables
  tidyverse)    # data management + ggplot2 graphics
```

```{r}
count_df <- import("/home/jeremy/Work/Development/Projects/epidemic/datasets/malaria_facility_count_data.rds")
linelist <- import("/home/jeremy/Work/Development/Projects/epidemic/datasets/linelist_cleaned.xlsx")
head(count_df)
head(linelist)
```

```{r}
ggplot(count_df) +
  geom_col(aes(x = data_date, y = malaria_tot), width = 1)
```

```{r}
names(count_df)
```

```{r}
long_df <- count_df %>%
  pivot_longer(
    cols = c("malaria_rdt_0-4", "malaria_rdt_5-14", "malaria_rdt_15", "malaria_tot")
  )

long_df
```

```{r}
count_df %>%
  pivot_longer(
    cols = starts_with(regex("malaria"))
  )
```

```{r}
count_df %>%
  pivot_longer(
    cols = 6:9
  )
```

```{r}
count_df %>%
  pivot_longer(
    cols = `malaria_rdt_0-4`:malaria_tot
  )
```

```{r}
long_df <- 
  count_df %>% 
  pivot_longer(
    cols = starts_with("malaria_"),
    names_to = "age_group",
    values_to = "counts"
  )

long_df
```

```{r}
ggplot(long_df) +
  geom_col(mapping = aes(x = data_date, y = counts, fill = age_group))
```

```{r}
long_df %>% 
  filter(age_group != "malaria_tot") %>% 
  ggplot() +
  geom_col(
    aes(x = data_date, y = counts, fill = age_group),
    width = 1
  )
```

```{r}
long_df <- 
  long_df %>% 
  mutate(
    date = date %>% lubridate::as_date(),
    observation = 
      observation %>% 
      str_remove_all("obs") %>% 
      as.numeric()
  )

long_df
```

```{r}
ggplot(data = long_df, mapping = aes(x = date, y = id, fill = status)) +
  geom_tile(colour = "black") +
  scale_fill_manual(
    values = 
      c("Healthy" = "lightgreen", 
        "Unwell" = "red", 
        "Missing" = "orange")
  )
```

```{r}
head(linelist)
```

```{r}
str_sort(names(linelist), decreasing = FALSE)
```

```{r}
df_wide <- 
  linelist %>% 
  count(age_cat, gender)

df_wide
```

```{r}
ggplot(df_wide) +
  geom_col(aes(x = age_cat, y = n, fill = gender))
```

```{r}
table_wide <- 
  df_wide %>% 
  pivot_wider(
    id_cols = age_cat,
    names_from = gender,
    values_from = n
  )

table_wide
```

```{r}
table_wide %>% 
  janitor::adorn_totals(c("row", "col")) %>%
  knitr::kable() %>%
  kableExtra::row_spec(row = 10, bold = TRUE) %>%
  kableExtra::column_spec(column = 5, bold = TRUE)
```

## Fill

```{r}
df1 <- 
  tibble::tribble(
       ~Measurement, ~Facility, ~Cases,
                  1,  "Hosp 1",     66,
                  2,  "Hosp 1",     26,
                  3,  "Hosp 1",      8,
                  1,  "Hosp 2",     71,
                  2,  "Hosp 2",     62,
                  3,  "Hosp 2",     70,
                  1,  "Hosp 3",     47,
                  2,  "Hosp 3",     70,
                  3,  "Hosp 3",     38,
       )

df1 
```

```{r}
df2 <- 
  tibble::tribble(
    ~Year, ~Measurement, ~Facility, ~Cases,
     2000,            1,  "Hosp 4",     82,
     2001,            2,  "Hosp 4",     87,
     2002,            3,  "Hosp 4",     46
  )

df2
```

```{r}
df_combined <- 
  bind_rows(df1, df2) %>% 
  arrange(Measurement, Facility)

df_combined
```

```{r}
df_combined %>% 
  fill(Year, .direction = "up")
```

```{r}
# Alternatively, we can rearrange the data so that we would need to 
# fill in a downward direction:
df_combined <- 
  df_combined %>% 
  arrange(Measurement, desc(Facility))

df_combined
```

```{r}
df_combined %>%
  fill(Year, .direction = "down")
```

```{r}
ggplot(df_combined) +
  aes(x = Year, y = Cases, fill = Facility) +
  geom_col()
```

```{r}
df_combined %>% 
  pivot_wider(
    id_cols = c(Measurement, Facility),
    names_from = "Year",
    values_from = "Cases"
  ) %>% 
  arrange(Facility) %>% 
  janitor::adorn_totals(c("row", "col")) %>% 
  knitr::kable() %>% 
  kableExtra::row_spec(row = 5, bold = TRUE) %>% 
  kableExtra::column_spec(column = 5, bold = TRUE) 
```

```{r}
df_combined %>% 
  pivot_wider(
    names_from = "Year",
    values_from = "Cases"
  ) %>% 
  knitr::kable()
```
